In [1]:
import numpy as np

In [2]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [3]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [4]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])